version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: DockerfileAPI
    volumes:
      - ./api:/app
    ports:
      - "5000:5000"
    links:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DB=finance
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - GOOGLE_API_KEY=YOURAPIKEY
      - OPENAI_API_KEY=YOURAPIKEY
      - GOOGLE_CSE=YOURCSE
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: DockerfileAPP
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - api
  attacker:
    build: 
      context: .
      dockerfile: DockerfileAttack
    volumes:
      - ./attacker:/app
    ports:
      - "1337:1337"
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: finance
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: